# Day - 29 DIY

**Q1. Problem Statement: Hypothesis Testing**

Write  a  Python  program  that  reads  the  Life  Expectancy  Data.csv  (provided  on LMS)  file  into  a  DataFrame,  then  drops  null  values  and performshypothesis testing for the given scenario.

H0:u= average life expectancy of Afghanistan is the same as the averageLife expectancy of the world (Null hypothesis)

H1:u= average life expectancy of Afghanistan is not the same as the average Life expectancy of the world (Alternate hypothesis)

1.Load the dataset into a data frame

2.Drop all missing values 

3.Take   the   mean   of   the   whole   target   variable   and   extract   data   from ‘Afghanistan’

4.consider  a  significance  level  of  0.05,  perform  a  T-tail  test  using  the  stats library and calculate P-value and conclude hypothesis testing.

In [20]:
#importing all the neccessary libraries
import pandas as pd
from scipy.stats import ttest_1samp

In [8]:
#1 Load the dataset
df = pd.read_csv("Life Expectancy Data.csv")
df

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,723.0,27,4.36,0.000000,68.0,31,27.1,...,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,44.3
2934,Zimbabwe,2003,Developing,715.0,26,4.06,0.000000,7.0,998,26.7,...,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5,44.5
2935,Zimbabwe,2002,Developing,73.0,25,4.43,0.000000,73.0,304,26.3,...,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0,44.8
2936,Zimbabwe,2001,Developing,686.0,25,1.72,0.000000,76.0,529,25.9,...,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8,45.3
2937,Zimbabwe,2000,Developing,665.0,24,1.68,0.000000,79.0,1483,25.5,...,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8,46.0

In [9]:
#2 Drop missing values
df.dropna(inplace=True)

In [12]:
#3 Extract life expectancy data for afghanistan
afghanistan_life_expectancy = df[df["Country"] == "Afghanisthan"] ["Life expectancy "]
afghanistan_life_expectancy

Series([], Name: Life expectancy , dtype: float64)

In [14]:
# Calculate the mean life expectancy globally
global_life_expectancy_mean = df['Life expectancy '].mean()
global_life_expectancy_mean

np.float64(69.3023044269254)

In [19]:
#4 Perform one-sample t-test
t_statistic, p_value = ttest_1samp(afghanistan_life_expectancy, global_life_expectancy_mean)

C:\Users\sravy\AppData\Local\Temp\ipykernel_14544\3358907365.py:2: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  t_statistic, p_value = ttest_1samp(afghanistan_life_expectancy, global_life_expectancy_mean)

In [17]:
# Set significance level
alpha = 0.05

In [18]:
# Conclusion
if p_value < alpha:
    print("We reject the null hypothesis")
    print("The average life expectancy of Afghanistan is not the same as the average life expectancy of the world.")
else:
    print("We fail to reject the null hypothesis")
    print("The average life expectancy of Afghanistan is the same as the average life expectancy of the world.")

We fail to reject the null hypothesis
The average life expectancy of Afghanistan is the same as the average life expectancy of the world.